#!/bin/bash

set -euo pipefail

VOICEMODE_HOME="${VOICEMODE_HOME:-$HOME/.voicemode}"
VOICEMODE_ENV="$VOICEMODE_HOME/voicemode.env"

if [ -f "$VOICEMODE_ENV" ]; then
  # shellcheck disable=SC1090
  . "$VOICEMODE_ENV"
fi

CLAWMUX_HOME="${CLAWMUX_HOME:-$HOME/.clawmux}"
LEGACY_WHISPER_DIR="$CLAWMUX_HOME/services/whisper"

WHISPER_DIR="${WHISPER_DIR:-$VOICEMODE_HOME/services/whisper}"
MODEL_DIR="$WHISPER_DIR/models"
BIN_DIR="$WHISPER_DIR/bin"
BUILD_BIN_DIR="$WHISPER_DIR/build/bin"

WHISPER_PORT="${CLAWMUX_WHISPER_PORT:-${VOICEMODE_WHISPER_PORT:-2022}}"
WHISPER_MODEL="${CLAWMUX_WHISPER_MODEL:-${VOICEMODE_WHISPER_MODEL:-large-v3}}"
MODEL_PATH="$MODEL_DIR/ggml-${WHISPER_MODEL}.bin"

LOG_DIR="${WHISPER_LOG_DIR:-$VOICEMODE_HOME/logs/whisper}"
PID_FILE="${WHISPER_PID_FILE:-$WHISPER_DIR/whisper.pid}"
SERVER_BIN="$BUILD_BIN_DIR/whisper-server"
SYSTEMD_UNIT_NAME="${WHISPER_SYSTEMD_UNIT_NAME:-voicemode-whisper.service}"
