name: VoiceChat
options:
  bundleIdPrefix: com.zeul
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
targets:
  VoiceChat:
    type: application
    platform: iOS
    sources:
      - VoiceChat
      - VoiceChatShared
    dependencies:
      - target: VoiceChatWidgetExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zeul.voicechat
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 25QMAKVCBN
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: VoiceChat/Info.plist

  VoiceChatWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - VoiceChatWidget
      - VoiceChatShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zeul.voicechat.widget
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 25QMAKVCBN
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: VoiceChatWidget/Info.plist
