/**
 * Theme management — applies VS Code CSS variables for dark/light mode.
 * Follows system preference automatically.
 */

const dark = {
  '--vscode-foreground': '#cccccc',
  '--vscode-descriptionForeground': '#9d9d9d',
  '--vscode-disabledForeground': '#6b6b6b',
  '--vscode-errorForeground': '#f48771',
  '--vscode-focusBorder': '#0078d4',
  '--vscode-editor-background': '#1e1e1e',
  '--vscode-editor-foreground': '#cccccc',
  '--vscode-editor-font-family': "'Fira Code','Cascadia Code','JetBrains Mono',Menlo,Monaco,'Courier New',monospace",
  '--vscode-editor-font-size': '13px',
  '--vscode-editor-lineHighlightBackground': '#2a2d2e',
  '--vscode-sideBar-background': '#181818',
  '--vscode-sideBarActivityBarTop-border': '#3c3c3c',
  '--vscode-input-background': '#2d2d2d',
  '--vscode-input-foreground': '#cccccc',
  '--vscode-input-border': '#3c3c3c',
  '--vscode-input-placeholderForeground': '#6b6b6b',
  '--vscode-inputOption-activeBorder': '#0078d4',
  '--vscode-inputOption-activeBackground': '#0078d422',
  '--vscode-inputOption-activeForeground': '#ffffff',
  '--vscode-inlineChatInput-border': '#3c3c3c',
  '--vscode-list-hoverBackground': '#2a2d2e',
  '--vscode-list-activeSelectionBackground': '#04395e',
  '--vscode-list-activeSelectionForeground': '#ffffff',
  '--vscode-list-inactiveSelectionBackground': '#37373d',
  '--vscode-menu-background': '#2d2d2d',
  '--vscode-menu-border': '#454545',
  '--vscode-menu-foreground': '#cccccc',
  '--vscode-menu-selectionBackground': '#04395e',
  '--vscode-menu-selectionForeground': '#ffffff',
  '--vscode-menu-separatorBackground': '#454545',
  '--vscode-button-background': '#0078d4',
  '--vscode-button-foreground': '#ffffff',
  '--vscode-button-hoverBackground': '#026ec1',
  '--vscode-button-secondaryBackground': '#3a3d41',
  '--vscode-button-secondaryForeground': '#cccccc',
  '--vscode-button-secondaryHoverBackground': '#45494e',
  '--vscode-badge-background': '#4d4d4d',
  '--vscode-badge-foreground': '#ffffff',
  '--vscode-progressBar-background': '#0078d4',
  '--vscode-widget-border': '#3c3c3c',
  '--vscode-widget-shadow': '#00000050',
  '--vscode-editorWidget-border': '#454545',
  '--vscode-editorWidget-background': '#252526',
  '--vscode-toolbar-hoverBackground': '#3c3c3c',
  '--vscode-sash-hoverBorder': '#0078d4',
  '--vscode-gitDecoration-addedResourceForeground': '#81b88b',
  '--vscode-gitDecoration-deletedResourceForeground': '#c74e39',
  '--vscode-gitDecoration-modifiedResourceForeground': '#e2c08d',
  '--vscode-charts-green': '#22c55e',
  '--vscode-charts-blue': '#3b82f6',
  '--vscode-scrollbarSlider-background': '#79797966',
  '--vscode-scrollbarSlider-hoverBackground': '#646464b3',
  '--vscode-scrollbarSlider-activeBackground': '#bfbfbf66',
  '--vscode-textLink-foreground': '#3794ff',
  '--vscode-textLink-activeForeground': '#3794ff',
  '--vscode-textPreformat-foreground': '#d7ba7d',
  '--vscode-textPreformat-background': '#ffffff1a',
  '--vscode-textBlockQuote-background': '#ffffff1a',
  '--vscode-textBlockQuote-border': '#007acc80',
  '--vscode-textCodeBlock-background': '#0a0a0a66',
  '--vscode-textSeparator-foreground': '#ffffff2e',
  '--vscode-keybindingLabel-background': '#ffffff11',
  '--vscode-keybindingLabel-foreground': '#cccccc',
  '--vscode-keybindingLabel-border': '#33333399',
  '--vscode-keybindingLabel-bottomBorder': '#44444499',
  '--vscode-icon-foreground': '#c5c5c5',
  '--vscode-panel-background': '#181818',
  '--vscode-panel-border': '#2b2b2b',
  '--vscode-panelTitle-activeBorder': '#e7e7e7',
  '--vscode-panelTitle-activeForeground': '#e7e7e7',
  '--vscode-panelTitle-inactiveForeground': '#9d9d9d',
  '--vscode-chat-font-size': '13px',
  '--vscode-chat-font-family': "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif",
  '--vscode-chat-slashCommandBackground': '#26477866',
  '--vscode-chat-slashCommandForeground': '#85b6ff',
  '--vscode-chat-requestBorder': '#ffffff1a',
  '--vscode-tab-activeBackground': '#1e1e1e',
  '--vscode-tab-inactiveBackground': '#2d2d2d',
  '--vscode-tab-border': '#252526',
  '--vscode-tab-activeBorderTop': '#e7e7e7',
  '--vscode-notificationCenterHeader-background': '#303031',
  '--vscode-notifications-background': '#252526',
  '--vscode-notifications-border': '#303031',
  '--vscode-dropdown-background': '#313131',
  '--vscode-dropdown-border': '#3c3c3c',
  '--vscode-dropdown-foreground': '#cccccc',
  '--vscode-checkbox-background': '#313131',
  '--vscode-checkbox-border': '#3c3c3c',
  '--vscode-checkbox-foreground': '#cccccc',
};

const light = {
  '--vscode-foreground': '#333333',
  '--vscode-descriptionForeground': '#717171',
  '--vscode-disabledForeground': '#a5a5a5',
  '--vscode-errorForeground': '#a1260d',
  '--vscode-focusBorder': '#0078d4',
  '--vscode-editor-background': '#ffffff',
  '--vscode-editor-foreground': '#333333',
  '--vscode-editor-font-family': "'Fira Code','Cascadia Code','JetBrains Mono',Menlo,Monaco,'Courier New',monospace",
  '--vscode-editor-font-size': '13px',
  '--vscode-editor-lineHighlightBackground': '#f0f0f0',
  '--vscode-sideBar-background': '#f3f3f3',
  '--vscode-sideBarActivityBarTop-border': '#d4d4d4',
  '--vscode-input-background': '#ffffff',
  '--vscode-input-foreground': '#333333',
  '--vscode-input-border': '#cecece',
  '--vscode-input-placeholderForeground': '#a5a5a5',
  '--vscode-inputOption-activeBorder': '#0078d4',
  '--vscode-inputOption-activeBackground': '#0078d422',
  '--vscode-inputOption-activeForeground': '#000000',
  '--vscode-inlineChatInput-border': '#cecece',
  '--vscode-list-hoverBackground': '#e8e8e8',
  '--vscode-list-activeSelectionBackground': '#0078d4',
  '--vscode-list-activeSelectionForeground': '#ffffff',
  '--vscode-list-inactiveSelectionBackground': '#e4e6f1',
  '--vscode-menu-background': '#ffffff',
  '--vscode-menu-border': '#c8c8c8',
  '--vscode-menu-foreground': '#333333',
  '--vscode-menu-selectionBackground': '#0078d4',
  '--vscode-menu-selectionForeground': '#ffffff',
  '--vscode-menu-separatorBackground': '#d4d4d4',
  '--vscode-button-background': '#0078d4',
  '--vscode-button-foreground': '#ffffff',
  '--vscode-button-hoverBackground': '#026ec1',
  '--vscode-button-secondaryBackground': '#e1e1e1',
  '--vscode-button-secondaryForeground': '#333333',
  '--vscode-button-secondaryHoverBackground': '#d4d4d4',
  '--vscode-badge-background': '#c4c4c4',
  '--vscode-badge-foreground': '#333333',
  '--vscode-progressBar-background': '#0078d4',
  '--vscode-widget-border': '#d4d4d4',
  '--vscode-widget-shadow': '#00000029',
  '--vscode-editorWidget-border': '#c8c8c8',
  '--vscode-editorWidget-background': '#f3f3f3',
  '--vscode-toolbar-hoverBackground': '#e8e8e8',
  '--vscode-sash-hoverBorder': '#0078d4',
  '--vscode-gitDecoration-addedResourceForeground': '#587c0c',
  '--vscode-gitDecoration-deletedResourceForeground': '#ad0707',
  '--vscode-gitDecoration-modifiedResourceForeground': '#895503',
  '--vscode-charts-green': '#16a34a',
  '--vscode-charts-blue': '#2563eb',
  '--vscode-scrollbarSlider-background': '#64646466',
  '--vscode-scrollbarSlider-hoverBackground': '#646464b3',
  '--vscode-scrollbarSlider-activeBackground': '#00000099',
  '--vscode-textLink-foreground': '#006ab1',
  '--vscode-textLink-activeForeground': '#006ab1',
  '--vscode-textPreformat-foreground': '#a31515',
  '--vscode-textPreformat-background': '#0000000a',
  '--vscode-textBlockQuote-background': '#f2f2f2',
  '--vscode-textBlockQuote-border': '#007acc80',
  '--vscode-textCodeBlock-background': '#dcdcdc66',
  '--vscode-textSeparator-foreground': '#0000002e',
  '--vscode-keybindingLabel-background': '#dddddd66',
  '--vscode-keybindingLabel-foreground': '#555555',
  '--vscode-keybindingLabel-border': '#cccccc66',
  '--vscode-keybindingLabel-bottomBorder': '#bbbbbb66',
  '--vscode-icon-foreground': '#424242',
  '--vscode-panel-background': '#ffffff',
  '--vscode-panel-border': '#e5e5e5',
  '--vscode-panelTitle-activeBorder': '#333333',
  '--vscode-panelTitle-activeForeground': '#333333',
  '--vscode-panelTitle-inactiveForeground': '#717171',
  '--vscode-chat-font-size': '13px',
  '--vscode-chat-font-family': "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif",
  '--vscode-chat-slashCommandBackground': '#d2ecff66',
  '--vscode-chat-slashCommandForeground': '#0f5fc2',
  '--vscode-chat-requestBorder': '#0000001a',
  '--vscode-tab-activeBackground': '#ffffff',
  '--vscode-tab-inactiveBackground': '#ececec',
  '--vscode-tab-border': '#f3f3f3',
  '--vscode-tab-activeBorderTop': '#333333',
  '--vscode-notificationCenterHeader-background': '#e7e7e7',
  '--vscode-notifications-background': '#ffffff',
  '--vscode-notifications-border': '#e7e7e7',
  '--vscode-dropdown-background': '#ffffff',
  '--vscode-dropdown-border': '#cecece',
  '--vscode-dropdown-foreground': '#333333',
  '--vscode-checkbox-background': '#ffffff',
  '--vscode-checkbox-border': '#cecece',
  '--vscode-checkbox-foreground': '#333333',
};

let current = window.matchMedia?.('(prefers-color-scheme: light)').matches ? 'light' : 'dark';

function apply(theme) {
  current = theme;
  const vars = theme === 'light' ? light : dark;
  const el = document.documentElement;
  for (const [k, v] of Object.entries(vars)) el.style.setProperty(k, v);
  el.classList.remove('vscode-dark', 'vscode-light');
  el.classList.add(theme === 'light' ? 'vscode-light' : 'vscode-dark');
}

// Apply on load + follow system changes
apply(current);
window.matchMedia?.('(prefers-color-scheme: dark)').addEventListener('change', (e) => {
  apply(e.matches ? 'dark' : 'light');
});

export function toggleTheme() {
  apply(current === 'dark' ? 'light' : 'dark');
}
export function getTheme() {
  return current;
}
